apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellospringapp-api-service
  namespace: hellospringapp
  labels:
    app: hellospringapp-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellospringapp-api
  template:
    metadata:
      labels:
        app: hellospringapp-api
    spec:
      containers:
      - name: hellospringapp-api
        image: 091499481377.dkr.ecr.us-east-1.amazonaws.com/hellospringapp:latest
        ports:
        - containerPort: 8080
