apiVersion: v1
kind: Service
metadata:
  name: hellospringapp-api-service
  labels:
    app: hellospringapp-api
spec:
  type: LoadBalancer
  selector:
    app: hellospringapp-api
  ports:
  - name: tcp
    port: 80
    targetPort: 8080
