version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  load-dependencies:
    docker:
      - image: cimg/openjdk:19.0.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

  compile-main:
    docker:
      - image: cimg/openjdk:19.0.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle compileJava

  compile-test:
    docker:
      - image: cimg/openjdk:19.0.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle compileTestJava

  lint-main:
    docker:
      - image: cimg/openjdk:19.0.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle checkstyleMain

  lint-test:
    docker:
      - image: cimg/openjdk:19.0.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle checkstyleTest

  test:
    docker:
      - image: cimg/openjdk:19.0.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle test

  build-jar:
    docker:
      - image: cimg/openjdk:19.0.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle bootJar
      - persist_to_workspace:
          root: build/libs
          paths:
            - HelloSpring-0.0.1-SNAPSHOT.jar
  build-and-push-image:
    docker:
      - image: docker:23.0.1-cli-alpine3.17
    steps:
      - checkout
      - setup_remote_docker
      - run: mkdir -p build/libs
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              aws-cli containerd docker-compose
      - attach_workspace:
          at: /build/libs
      - aws-ecr/build-and-push-image:
          repo: hellospringapp
          tag: latest,$CIRCLE_SHA1

workflows:
  default:
    jobs:
      - load-dependencies
      - compile-main:
          requires: [load-dependencies]
      - compile-test:
          requires: [load-dependencies]
      - lint-main:
          requires: [load-dependencies]
      - lint-test:
          requires: [load-dependencies]
      - test:
          requires: [load-dependencies]
      - build-jar:
          requires: [test, lint-test, lint-main, compile-main, compile-test]
      - build-and-push-image:
          requires: [build-jar]