version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  load-dependencies:
    docker:
      - image: cimg/openjdk:19.0.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

  compile-main:
    docker:
      - image: cimg/openjdk:19.0.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle compileJava

  compile-test:
    docker:
      - image: cimg/openjdk:19.0.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle compileTestJava

  lint-main:
    docker:
      - image: cimg/openjdk:19.0.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle checkstyleMain

  lint-test:
    docker:
      - image: cimg/openjdk:19.0.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle checkstyleTest

  test:
    docker:
      - image: cimg/openjdk:19.0.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle test

  build-jar:
    docker:
      - image: cimg/openjdk:19.0.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle bootJar
      - persist_to_workspace:
          root: build/libs
          paths:
            - HelloSpring-0.0.1-SNAPSHOT.jar
  build-and-push-image:
    docker:
      - image: docker
    steps:
      - checkout
      - run: mkdir -p build/libs
      - attach_workspace:
          at: /build/libs
      - aws-ecr/build-and-push-image:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: SECRET_ACCAWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
          registry-id: AWS_ECR_REGISTRY_ID
          repo: hellospringapp
          tag: 'latest, hellospringapp'

workflows:
  default:
    jobs:
      - load-dependencies
      - compile-main:
          requires: [load-dependencies]
      - compile-test:
          requires: [load-dependencies]
      - lint-main:
          requires: [load-dependencies]
      - lint-test:
          requires: [load-dependencies]
      - test:
          requires: [load-dependencies]
      - build-jar:
          requires: [test, lint-test, lint-main, compile-main, compile-test]
      - build-and-push-image:
          requires: [build-jar]